
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jul 13 23:58:34 BRT 2017
//----------------------------------------------------

package teste;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int LEFTBRACKET = 23;
  public static final int MULT = 27;
  public static final int ME = 18;
  public static final int RIGHTPAREN = 22;
  public static final int XOR = 33;
  public static final int PE = 17;
  public static final int RIGHTBRACKET = 24;
  public static final int MINUS = 26;
  public static final int WRITE = 15;
  public static final int LEFTPAREN = 21;
  public static final int NOT = 30;
  public static final int AND = 31;
  public static final int LT = 34;
  public static final int OR = 32;
  public static final int CALL = 12;
  public static final int FI = 7;
  public static final int DIV = 28;
  public static final int UNTIL = 11;
  public static final int NUM = 3;
  public static final int LOOP = 10;
  public static final int PLUS = 25;
  public static final int IF = 4;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int XE = 19;
  public static final int MOD = 29;
  public static final int IDENT = 16;
  public static final int EQ = 38;
  public static final int FROM = 8;
  public static final int ELSE = 6;
  public static final int ILLEGAL_CHAR = 40;
  public static final int READ = 14;
  public static final int THEN = 5;
  public static final int GEQT = 37;
  public static final int LEQT = 35;
  public static final int UNCALL = 13;
  public static final int GT = 36;
  public static final int SWAP = 20;
  public static final int PROCEDURE = 2;
  public static final int DO = 9;
  public static final int NOTEQ = 39;
}

